name: pdgrapher
channels:
  - conda-forge
  - conda-canary
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - boost
  - boost-cpp
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cycler
  - fftw
  - fontconfig
  - freetype
  - glib
  - icu
  #- intel-openmp
  - jpeg
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - libopenblas
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  #- numpy-base
  - olefile
  - openssl
  - pcre
  - pixman
  - pycairo
  - python=3.8  # Kept the Python version to match your requirement
  - python-dateutil
  - python_abi
  - pytz
  - rdkit
  - readline
  - reportlab
  - six
  - sqlite
  - tk
  - tornado
  - xz
  - zlib
  - zstd
